### ISSUE TITLE
download.qt.io has dropped qt 5.8 files

### ISSUE THREAD

**Issue by dballard** [Orange-OpenSource/qmljsreformatter#10]
> Download at least the Qt 5.8 source version: https://download.qt.io/archive/qt/5.8/5.8.0/single/qt-everywhere-opensource-src-5.8.0.tar.gz.mirrorlist

dead link

found via google at a mirror 

https://ftp.osuosl.org/pub/blfs/conglomeration/qt5/?C=M;O=A

that hasn't deleted them

**Comment by julien-deramond** [comment]
Thank you @dballard. Indeed it is not possible anymore to download the sources. 

I think I'm going to describe how to clone and compile the Qt 5.8 sources rather than providing the link.

**Comment by julien-deramond** [comment]
For information, the simplest way is now to clone the Qt 5.12.8 sources.

I got some problems with the Qt 5.8 and 5.9 versions on both Ubuntu and macOS:

-  5.8 is not maintained anymore so a lot of patches are missing to compile with GCC 9 for example on Ubuntu
-  qmljsreformatter linking problems on macOS with the 5.9 version
